name: Build
on: push

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Save
        uses: action-owner/action-repo@ref

      - name: Push
        run: ./scripts/workflow-push.sh
