name: Build
on: push

jobs:
  job1:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Push
        run: |
          git config --global user.name "Workflow"
          git config --global user.email "elias.skogevall@gmail.com"

          git add -A
          git commit -m "commit message"
          git push
